# Generated by Django 6.1.1 on 2026-09-15 03:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.CharField(blank=True, max_length=140)),
                ('favorite_structure', models.CharField(blank=True, choices=[('', 'Not set yet'), ('array', 'Arrays'), ('linked_list', 'Linked Lists'), ('stack', 'Stacks'), ('queue', 'Queues'), ('tree', 'Trees'), ('graph', 'Graphs')], max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
