# Generated by Django 6.1.1 on 2026-09-21 21:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Snippet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('code', models.TextField()),
                ('data_structure', models.CharField(blank=True, choices=[('', 'Not specified'), ('array', 'Array'), ('linked_list', 'Linked List'), ('stack', 'Stack'), ('queue', 'Queue'), ('tree', 'Tree'), ('graph', 'Graph')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snippets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TraceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicted_time_complexity', models.CharField(blank=True, choices=[('', 'Not sure'), ('O(1)', 'O(1) — constant'), ('O(log n)', 'O(log n) — logarithmic'), ('O(n)', 'O(n) — linear'), ('O(n log n)', 'O(n log n) — linearithmic'), ('O(n^2)', 'O(n²) — quadratic'), ('O(2^n)', 'O(2ⁿ) — exponential')], max_length=20)),
                ('predicted_space_complexity', models.CharField(blank=True, choices=[('', 'Not sure'), ('O(1)', 'O(1) — constant'), ('O(log n)', 'O(log n) — logarithmic'), ('O(n)', 'O(n) — linear'), ('O(n log n)', 'O(n log n) — linearithmic'), ('O(n^2)', 'O(n²) — quadratic'), ('O(2^n)', 'O(2ⁿ) — exponential')], max_length=20)),
                ('actual_time_complexity', models.CharField(blank=True, max_length=20)),
                ('actual_space_complexity', models.CharField(blank=True, max_length=20)),
                ('operation_count', models.IntegerField(default=0)),
                ('error_message', models.CharField(blank=True, max_length=255)),
                ('is_saved', models.BooleanField(default=False)),
                ('traced_at', models.DateTimeField(auto_now_add=True)),
                ('snippet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='tracer.snippet')),
            ],
        ),
        migrations.CreateModel(
            name='TraceStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.IntegerField()),
                ('line_number', models.IntegerField()),
                ('variables_snapshot', models.JSONField(default=dict)),
                ('structure_snapshot', models.JSONField(blank=True, default=None, null=True)),
                ('trace_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='tracer.tracesession')),
            ],
            options={
                'ordering': ['step_number'],
            },
        ),
    ]
