# Generated by Django 6.1.1 on 2026-10-07 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracestep',
            name='output',
            field=models.TextField(blank=True, default=''),
        ),
    ]
